FACT-1963 - Notification Sending and Notification Status APIs
hmcts/reform-scan-notification-service pull request #1616
Opened 2024-09-26 14:40 UTC by RuthKirby

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/FACT-1963

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-10-14 11:59 UTC, joshblackmoor requested changes
Great work, added one small comment but probably missing the context since I've been off

2024-10-14 11:59 UTC, joshblackmoor commented on src/main/resources/db/migration/V012__remove_message_id_constraint.sql
> +ALTER TABLE notifications
not 100% sure about this, may need to discuss with you.

2024-10-14 19:36 UTC, joshblackmoor commented on src/main/resources/db/migration/V012__remove_message_id_constraint.sql
> +ALTER TABLE notifications
Makes sense, its not providing us a lot of value currently anyway and will obviously be removed upon us switching to this new API so all good. 

Will need to remember during testing to run this script against demo just so we covered it off

2024-10-14 19:36 UTC, joshblackmoor approved these changes

2024-10-15 11:31 UTC, justiceia approved these changes

2024-10-22 08:35 UTC, merged