DTSBPS-369: bump springboot 2.4.2
hmcts/reform-scan-notification-service pull request #382
Opened 2021-02-18 19:36 UTC by rishikrsharma

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-18 20:11 UTC, apereverzin requested changes
Please, break it into 2 PRs: suppression and upgrade.

2021-02-19 09:30 UTC, SomeshRA approved these changes

2021-02-19 09:58 UTC, rishikrsharma commented
> Please, break it into 2 PRs: suppression and upgrade.

It has been done. Now only upgrade in this PR.

2021-02-19 11:24 UTC, mdayican approved these changes

2021-02-19 11:25 UTC, merged